### ISSUE TITLE
Nan's bepalen

### ISSUE THREAD

**Issue by MartijnJansenPro** [racheldijkstra/WTCarInsurance#10]
Het invullen of verwijderen van de NaN values, en bepalen hoe dit moet gebeuren.

**Comment by racheldijkstra** [comment]
Het invullen of verwijderen van de NaN values, en bepalen hoe dit moet gebeuren.

**Comment by racheldijkstra** [comment]
Deze taak vervalt door het wijzigen van de planning. Deze dataset zal niet meer gebruikt worden.
