### ISSUE TITLE
nieuwe dataset

### ISSUE THREAD

**Issue by MartijnJansenPro** [racheldijkstra/WTCarInsurance#11]
Bij deze taak is het de bedoeling om naar data te zoeken die een beter beeld geeft van de auto ongelukken dan de huidige data.

**Comment by racheldijkstra** [comment]
Op de volgende site is veel data te vinden over crashes in amerika: [https://cdan.dot.gov/](url). Echter is er alleen bij de fatale crashes data over in welke staat dit gebeurd is. Bij de crashes waarbij er sprake is van injuries, property damage, of beide, wordt geen staat vermeld.
