### ISSUE TITLE
Requirements voor WT Car Insurance

### ISSUE THREAD

**Issue by MartijnJansenPro** [racheldijkstra/WTCarInsurance#24]
WT Car Insurance wilt doorbreken in de Amerikaanse markt. Hiervoor moet data worden verzameld die inzicht bied in de Amerikaanse markt per staat. Allereerst moeten hiervoor factoren in kaart worden gebracht die relevant zijn voor dit onderzoek. Deze factoren moeten vervolgens met de stakeholder worden gecommuniceerd

**Comment by racheldijkstra** [comment]
# Rapport risico factoren

In het volgende rapport zullen wij toelichten welke factoren wij belangrijk vinden om te onderzoeken voor WT Car Insurance. Dit zullen wij onderbouwen met literatuur. Wij zullen een kort overzicht geven van de geschatte kosten en baten van het bedrijf, en zullen ook alvast refereren naar gevonden data(sets).

## Kosten (Risico)
Het risicio voor het verzekeringsbedrijf kan voortkomen uit een hoop verschillende factoren. Elk van deze factoren moet zo klein mogelijk zijn voor een staat om door WT car insurance voordelig te zijn. Hieronder zullen we een aantal factoren noemen die bijdragen aan een verhoogd risico. 

De kosten voor WT car insurance komen voort uit de uitbetalingen die het bedrijf moet doen voor een verzekerd persoon. Dit kan zijn een gestolen voertuig, een kapot voertuig (door achterstalligheid), schade aan het voertuig (door criminaliteit of een ongeluk) of letsel aan een persoon. Dat laatste zorgt vaak voor de hoogste kosten. 

Volgens een Amerikaans advocaten bureau (i) zijn dit de geschatte kosten voor een ongeluk:
- Death – $1,778,000
- Disabling Injury – $155,000
- Evident Injury – $40,000
- Possible Injury – $24,000
- No Injury – $6,700
- Property damage Only – $5,700

Verder kunnen wij aan de hand van data over de totale uitgekeerde auto verzekeringskosten per staat (vi) ook een inschatting maken over de kosten die het verzekeringsbedrijf gemiddeld zou moeten maken per staat. 

Met een gevonden dataset (v) kunnen we zien in welke staat de meeste doden vallen door auto ongelukken. Echter is het duidelijk dat persoonlijk letsel en schade ook voorkomen moeten worden. We zullen de factoren die het meeste bijdragen aan persoonlijk letsel en auto schade documenteren en in een database uitzetten. Verder zullen wij auto gerelateerde criminaliteit ook meenemen als factor, aangezien veel auto verzekeringsmaatschappijen ook een optie aanbieden om tegen bijvoorbeeld diefstal te verzekeren.

Onder dit soort factoren bestaan onder andere:
- Driving record
    - Rijden onder invloed (vii, viii)
    - Verzekeringsclaims gemaakt
    - Aantal ongelukken
    - Verkeers overtredingen / Rijgedrag
        - Snelheidsovertreding (ix)
- Inwoners profiel 
    - Rijervaring
    - Leeftijd (ii)
    - Geslacht (ii)
    - Opleidingsniveau
- Criminaliteit (vii)
- Weersomstandigheden
- Auto kenmerken 
    - leeftijd auto
    - type auto
    - totaal gereden kilometers

### Toelichting risico factoren
**Rijden onder invloed:**
Het rijden onder invloed heeft een significante invloed op de risico’s voor zichzelf en andere in het verkeer. Zo is het risico op een fataal ongeluk 7x groter met alcohol in het bloed (x). Verder vormen bestuurders die volgens de standaarden in de wet dronken zijn een 13x groter risico dan nuchtere bestuurders (x). Elke gereden mile door een bestuurder onder invloed kost 30 cent extra (x). Het rijden onder invloed zou verder zelfs een van de factoren zijn met de grootste invloed op het risico op een ongeluk (xx). Om deze reden is het handig om te weten hoeveel mensen er per staat onder invloed rijden. 

**Verkeersovertredingen / rijgedrag:**
Verkeersovertredingen, naast rijden onder invloed, hebben ook invloed op het aantal ongelukken. Zo is er uit een studie gebleken dat factoren die invloed hebben op het intieren van een fataal ongeluk zijn; het niet dragen van een gordel en het rijden zonder rijbewijs (xx). Hiernaast is er ook gevonden dat mensen die al eerder betrokken geweest zijn bij een ongeluk (binnen het laatste jaar), ook een groter risico vormen voor een (fataal) ongeluk. Dit laatste legt ook uit waarom het nuttig is om te weten hoeveel autoverzekeringsclaims er zijn gemaakt in een staat.

**Inwoners profiel:**
Uit onderzoek is gebleken dat bepaalde eigenschappen van mensen de kans op ongelukken vergroot. Zo zijn bepaalde leeftijdsklassen een risicofactor. De groep bestuurders van 18-24 jaar oud zijn verantwoordelijk voor 23% van de dodelijke ongelukken (xvi). Verder zijn ouderen meer kwetsbaar in het verkeer, waardoor zij een groter risico lopen op zwaar letsel of zelfs overlijden in een auto ongeluk (xvii). Dit zou voor een verzekering dus hogere kosten kunnen betekenen bij specifieke pakketten. 

Een andere studie ziet een sterke correlatie tussen het aantal jaren dat iemand in bezit is van een rijbewijs, en het risico op een ongeluk in een jonge subject group van 16-29 jaar (xviii). Het aantal jaren rijervaring heeft een positief effect op het aantal ongelukken. 

Verder lijkt er ook een verband te zijn tussen opleidingsniveau en het risico op ongelukken (xix). Mensen met hooguit een high school degree zouden 4x zoveel kans hebben om om te komen in een auto ongeluk dan mensen met een college degree. Hoger opgeleide individuen zouden ook minder met alcohol achter het stuur stappen, en vaker een gordel gebruiken, wat een deel van een verklaring zou kunnen zijn voor het probleem. Verder wordt er ook kort genoemd dat mannen de meeste auto ongelukken veroorzaken, en dat het opleidingsniveau daarom vooral onder hen veel invloed heeft. 

Data over de leeftijd, het geslacht, het opleidingsniveau en het aantal jaren rijervaring van de inwoners van een staat is dus nuttige informatie voor de risico analyse.

**Criminaliteit:**
Auto diefstal is een factor die meespeelt voor een auto verzekering. “The total cost of auto theft to the U.S. in 1985 is estimated at $6 billion at current prices, or about $45 per automobile per year” (xiv). Als er in bepaalde gebieden relatief heel veel meer autos gestolen worden dan is het handig om dat mee te nemen in ons besluit. Ook is Joyriden een probleem (xv). In bepaalde gebieden, voornamelijk achtergestelde binnenstedelijke wijken, is er sprake van een toename van deze criminaliteit. In totaal werden 1576 patiënten opgenomen op de traumadienst. Honderdtweeënvijftig opnames waren het gevolg van een verkeersongeval en 20 (13 procent) van deze patiënten hadden letsel als gevolg van autodiefstal. Van deze groep waren er acht ernstig gewond (ISS > 16) en zes van hen waren onschuldige omstanders. Drie patiënten (één joyrider en twee onschuldige omstanders) overleden als gevolg van autodiefstal. De gemiddelde duur van het ziekenhuisverblijf was 12 dagen (1-62 dagen) en de ziekenhuiskosten per patiënt werden geschat op minstens £5200. Het kan dus helpen als we ook kijken naar welke staten de meeste joyriders bevinden om dat enigzins mee te nemen in ons uiteindelijk besluit.

**Weersomstandigheden:**
Er is bewijs (xiii) dat de waarschijnlijkheid van verschillende soorten verkeersongevallen verandert bij ongunstige weersomstandigheden, zoals neerslag, zonneschittering en hoge windsnelheden. Zo blijkt bijvoorbeeld dat sneeuw een aanzienlijk effect heeft op ongevallen met vrachtwagens, terwijl regen een grotere impact heeft op ongevallen met auto's. Zonneschittering vergroot de kans op ongevallen met meerdere auto's, vooral bij hogere snelheden en bij kop-staart-botsingen. Hoge windsnelheden worden geassocieerd met een verhoogde kans op ongevallen met enkele vrachtwagens en ongevallen waarbij objecten op de weg worden geblazen.

**Auto kenmerken:**
Uit onderzoek (xii) blijkt dat de overlevingskansen sterk afhankelijk zijn van het type auto. Moderne auto’s hebben meer veiligheidssystemen die zorgen voor minder ongelukken. De auto kijkt mee met de bestuurder waardoor er altijd een extra check is en daardoor dus een gereduceerde kans op ongevallen. Hierdoor maakt de leeftijd dus ook veel uit van de auto. Hoe ouder de auto, hoe minder aanwezige veiligheidssystemen. In de loop van de jaren is ook de kreukelzone verbeterd van auto’s. Hoe nieuwer de auto, hoe beter de kreukelzone. Echter geldt hierbij ook dat hoe groter de auto, hoe groter de kreukelzone, hoe kleiner de impact bij een ongeluk. Echter geld ook dat hoe groter en nieuwer de auto, hoe duurder. Bij een ongeluk met een nieuwe, grote auto is dus de verwachting dat menselijk letsel minder kost, maar de auto wel duurder is om te repareren vanwege alle slimme systemen en sensoren aan boord. Vuistregel is natuurlijk wel dat een mensen leven altijd duurder en kostbaarder is dan een auto.

## Baten (Geschatte omzet)
Tegenover risico factoren zullen we ook uitzoeken in welke staten WT car insurance het meeste omzet kan behalen. Dit is eenvoudig uit te zoeken door te kijken naar het aantal mensen met een rijbewijs (iv) en de gemiddelde verzekeringspremie (iii) per staat. 

## Referenties

1. https://www.goldlaw.com/how-much-does-the-average-car-accident-cost/
2. https://datahub.transportation.gov/Roadways-and-Bridges/Licensed-Drivers-by-state-gender-and-age-group/xfkb-3bxx
3. [Car Insurance Costs by US state (kaggle.com)](https://www.kaggle.com/datasets/andrewmvd/car-insurance-costs)
4. https://datahub.transportation.gov/Roadways-and-Bridges/Licensed-Drivers-by-state-gender-and-age-group/xfkb-3bxx
5. https://www-fars.nhtsa.dot.gov/States/StatesCrashesAndAllVictims.aspx
6. https://www.iii.org/table-archive/21212
7. https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/explorer/crime/arrest
8. https://www-fars.nhtsa.dot.gov/States/StatesAlcohol.aspx
9. https://cdan.dot.gov/SASJobExecution/
10. Levitt, S., & Porter, J. (2001). How Dangerous Are Drinking Drivers?. Journal of Political Economy, 109, 1198 - 1237. https://doi.org/10.1086/323281.
11. Backman, M., & , M. (1984). INSURANCE POLICY, RISK TAKING AND SAFETY IN TRAFFIC. Technical reports.
12. https://www.sciencedirect.com/science/article/abs/pii/S0001457509002759?via%3Dihub
13. Becker, N., Rust, H. W., & Ulbrich, U. (2022). Weather impacts on various types of road crashes: a quantitative analysis using generalized additive models. European transport research review, 14(1), 1-18.
14. Field, S. (1993). Crime prevention and the costs of auto theft: An economic analysis. Crime prevention studies, 1, 69-91.
15. Marshall, C., Boyd, K. T., & Moran, C. G. (1996). Injuries related to car crime: the joy-riding epidemic. Injury, 27(2), 79-80.
16. Gicquel, L., Ordonneau, P., Blot, E., Toillon, C., Ingrand, P., & Romo, L. (2017). Description of Various Factors Contributing to Traffic Accidents in Youth and Measures Proposed to Alleviate Recurrence. Frontiers in Psychiatry, 8. https://doi.org/10.3389/fpsyt.2017.00094.
17. Mcknight, A. (2001). TOO OLD TO DRIVE. Issues in Science and Technology, 17.
18. Trimpop, R., & Kirkcaldy, B. (1997). Personality predictors of driving accidents. Personality and Individual Differences, 23, 147-152. https://doi.org/10.1016/S0191-8869(97)00017-2.
19. Cox, R., & Grant, D. (2016). Traffic Safety and Human Capital. Environment for Innovation eJournal. https://doi.org/10.2139/ssrn.2886500.
20. Perneger, T., & Smith, G. (1991). The driver's role in fatal two-car crashes: a paired "case-control" study.. American journal of epidemiology, 134 10, 1138-45. https://doi.org/10.1093/OXFORDJOURNALS.AJE.A116017.
