### ISSUE TITLE
Data voor gestelde requirements

### ISSUE THREAD

**Issue by MartijnJansenPro** [racheldijkstra/WTCarInsurance#25]
Voor de gevonden en geverifieerde requirements moet data worden gevonden via openbaar toegangelijke en relatief betrouwbare bronnen.

**Comment by JoeyMoes** [comment]
Deze taak is een overkoepelende taak dat uit de volgende kleinere issues bestaat:
#34 
#35 
#36 
#37 
#38 
#39 
#41 
#42

**Comment by MartijnJansenPro** [comment]
data is gevonden en staat in docs teams
